version: '3'

services:
  db:
    image: postgres:15
    container_name: terra-ignota
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: terra-ignota
